
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.2.0.1)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace HRModuleEntity
{
	public abstract class _BankDetail : SqlClientEntity
	{
		public _BankDetail()
		{
			this.QuerySource = "BankDetail";
			this.MappingName = "BankDetail";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_BankDetailLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int ID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.ID, ID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_BankDetailLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter ID
			{
				get
				{
					return new SqlParameter("@ID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter AccountNo
			{
				get
				{
					return new SqlParameter("@AccountNo", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AccountHolder
			{
				get
				{
					return new SqlParameter("@AccountHolder", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter Branch
			{
				get
				{
					return new SqlParameter("@Branch", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter EmpID
			{
				get
				{
					return new SqlParameter("@EmpID", SqlDbType.BigInt, 0);
				}
			}
			
			public static SqlParameter CurrentBank
			{
				get
				{
					return new SqlParameter("@CurrentBank", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter CreationDate
			{
				get
				{
					return new SqlParameter("@CreationDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter CreatedBy
			{
				get
				{
					return new SqlParameter("@CreatedBy", SqlDbType.BigInt, 0);
				}
			}
			
			public static SqlParameter ModifiedDate
			{
				get
				{
					return new SqlParameter("@ModifiedDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter ModifiedBy
			{
				get
				{
					return new SqlParameter("@ModifiedBy", SqlDbType.BigInt, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string ID = "ID";
            public const string Name = "Name";
            public const string AccountNo = "AccountNo";
            public const string AccountHolder = "AccountHolder";
            public const string Branch = "Branch";
            public const string EmpID = "EmpID";
            public const string CurrentBank = "CurrentBank";
            public const string CreationDate = "CreationDate";
            public const string CreatedBy = "CreatedBy";
            public const string ModifiedDate = "ModifiedDate";
            public const string ModifiedBy = "ModifiedBy";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ID] = _BankDetail.PropertyNames.ID;
					ht[Name] = _BankDetail.PropertyNames.Name;
					ht[AccountNo] = _BankDetail.PropertyNames.AccountNo;
					ht[AccountHolder] = _BankDetail.PropertyNames.AccountHolder;
					ht[Branch] = _BankDetail.PropertyNames.Branch;
					ht[EmpID] = _BankDetail.PropertyNames.EmpID;
					ht[CurrentBank] = _BankDetail.PropertyNames.CurrentBank;
					ht[CreationDate] = _BankDetail.PropertyNames.CreationDate;
					ht[CreatedBy] = _BankDetail.PropertyNames.CreatedBy;
					ht[ModifiedDate] = _BankDetail.PropertyNames.ModifiedDate;
					ht[ModifiedBy] = _BankDetail.PropertyNames.ModifiedBy;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string ID = "ID";
            public const string Name = "Name";
            public const string AccountNo = "AccountNo";
            public const string AccountHolder = "AccountHolder";
            public const string Branch = "Branch";
            public const string EmpID = "EmpID";
            public const string CurrentBank = "CurrentBank";
            public const string CreationDate = "CreationDate";
            public const string CreatedBy = "CreatedBy";
            public const string ModifiedDate = "ModifiedDate";
            public const string ModifiedBy = "ModifiedBy";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ID] = _BankDetail.ColumnNames.ID;
					ht[Name] = _BankDetail.ColumnNames.Name;
					ht[AccountNo] = _BankDetail.ColumnNames.AccountNo;
					ht[AccountHolder] = _BankDetail.ColumnNames.AccountHolder;
					ht[Branch] = _BankDetail.ColumnNames.Branch;
					ht[EmpID] = _BankDetail.ColumnNames.EmpID;
					ht[CurrentBank] = _BankDetail.ColumnNames.CurrentBank;
					ht[CreationDate] = _BankDetail.ColumnNames.CreationDate;
					ht[CreatedBy] = _BankDetail.ColumnNames.CreatedBy;
					ht[ModifiedDate] = _BankDetail.ColumnNames.ModifiedDate;
					ht[ModifiedBy] = _BankDetail.ColumnNames.ModifiedBy;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string ID = "s_ID";
            public const string Name = "s_Name";
            public const string AccountNo = "s_AccountNo";
            public const string AccountHolder = "s_AccountHolder";
            public const string Branch = "s_Branch";
            public const string EmpID = "s_EmpID";
            public const string CurrentBank = "s_CurrentBank";
            public const string CreationDate = "s_CreationDate";
            public const string CreatedBy = "s_CreatedBy";
            public const string ModifiedDate = "s_ModifiedDate";
            public const string ModifiedBy = "s_ModifiedBy";

		}
		#endregion		
		
		#region Properties
	
		public virtual int ID
	    {
			get
	        {
				return base.Getint(ColumnNames.ID);
			}
			set
	        {
				base.Setint(ColumnNames.ID, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual int AccountNo
	    {
			get
	        {
				return base.Getint(ColumnNames.AccountNo);
			}
			set
	        {
				base.Setint(ColumnNames.AccountNo, value);
			}
		}

		public virtual string AccountHolder
	    {
			get
	        {
				return base.Getstring(ColumnNames.AccountHolder);
			}
			set
	        {
				base.Setstring(ColumnNames.AccountHolder, value);
			}
		}

		public virtual string Branch
	    {
			get
	        {
				return base.Getstring(ColumnNames.Branch);
			}
			set
	        {
				base.Setstring(ColumnNames.Branch, value);
			}
		}

		public virtual long EmpID
	    {
			get
	        {
				return base.Getlong(ColumnNames.EmpID);
			}
			set
	        {
				base.Setlong(ColumnNames.EmpID, value);
			}
		}

		public virtual bool CurrentBank
	    {
			get
	        {
				return base.Getbool(ColumnNames.CurrentBank);
			}
			set
	        {
				base.Setbool(ColumnNames.CurrentBank, value);
			}
		}

		public virtual DateTime CreationDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.CreationDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.CreationDate, value);
			}
		}

		public virtual long CreatedBy
	    {
			get
	        {
				return base.Getlong(ColumnNames.CreatedBy);
			}
			set
	        {
				base.Setlong(ColumnNames.CreatedBy, value);
			}
		}

		public virtual DateTime ModifiedDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.ModifiedDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.ModifiedDate, value);
			}
		}

		public virtual long ModifiedBy
	    {
			get
	        {
				return base.Getlong(ColumnNames.ModifiedBy);
			}
			set
	        {
				base.Setlong(ColumnNames.ModifiedBy, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_ID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ID) ? string.Empty : base.GetintAsString(ColumnNames.ID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ID);
				else
					this.ID = base.SetintAsString(ColumnNames.ID, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_AccountNo
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AccountNo) ? string.Empty : base.GetintAsString(ColumnNames.AccountNo);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AccountNo);
				else
					this.AccountNo = base.SetintAsString(ColumnNames.AccountNo, value);
			}
		}

		public virtual string s_AccountHolder
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AccountHolder) ? string.Empty : base.GetstringAsString(ColumnNames.AccountHolder);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AccountHolder);
				else
					this.AccountHolder = base.SetstringAsString(ColumnNames.AccountHolder, value);
			}
		}

		public virtual string s_Branch
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Branch) ? string.Empty : base.GetstringAsString(ColumnNames.Branch);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Branch);
				else
					this.Branch = base.SetstringAsString(ColumnNames.Branch, value);
			}
		}

		public virtual string s_EmpID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EmpID) ? string.Empty : base.GetlongAsString(ColumnNames.EmpID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EmpID);
				else
					this.EmpID = base.SetlongAsString(ColumnNames.EmpID, value);
			}
		}

		public virtual string s_CurrentBank
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CurrentBank) ? string.Empty : base.GetboolAsString(ColumnNames.CurrentBank);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CurrentBank);
				else
					this.CurrentBank = base.SetboolAsString(ColumnNames.CurrentBank, value);
			}
		}

		public virtual string s_CreationDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CreationDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.CreationDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CreationDate);
				else
					this.CreationDate = base.SetDateTimeAsString(ColumnNames.CreationDate, value);
			}
		}

		public virtual string s_CreatedBy
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CreatedBy) ? string.Empty : base.GetlongAsString(ColumnNames.CreatedBy);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CreatedBy);
				else
					this.CreatedBy = base.SetlongAsString(ColumnNames.CreatedBy, value);
			}
		}

		public virtual string s_ModifiedDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ModifiedDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.ModifiedDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ModifiedDate);
				else
					this.ModifiedDate = base.SetDateTimeAsString(ColumnNames.ModifiedDate, value);
			}
		}

		public virtual string s_ModifiedBy
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ModifiedBy) ? string.Empty : base.GetlongAsString(ColumnNames.ModifiedBy);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ModifiedBy);
				else
					this.ModifiedBy = base.SetlongAsString(ColumnNames.ModifiedBy, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ID, Parameters.ID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AccountNo
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AccountNo, Parameters.AccountNo);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AccountHolder
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AccountHolder, Parameters.AccountHolder);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Branch
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Branch, Parameters.Branch);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EmpID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EmpID, Parameters.EmpID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CurrentBank
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CurrentBank, Parameters.CurrentBank);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CreationDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CreationDate, Parameters.CreationDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CreatedBy
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CreatedBy, Parameters.CreatedBy);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ModifiedDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ModifiedDate, Parameters.ModifiedDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ModifiedBy
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ModifiedBy, Parameters.ModifiedBy);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter AccountNo
		    {
				get
		        {
					if(_AccountNo_W == null)
	        	    {
						_AccountNo_W = TearOff.AccountNo;
					}
					return _AccountNo_W;
				}
			}

			public WhereParameter AccountHolder
		    {
				get
		        {
					if(_AccountHolder_W == null)
	        	    {
						_AccountHolder_W = TearOff.AccountHolder;
					}
					return _AccountHolder_W;
				}
			}

			public WhereParameter Branch
		    {
				get
		        {
					if(_Branch_W == null)
	        	    {
						_Branch_W = TearOff.Branch;
					}
					return _Branch_W;
				}
			}

			public WhereParameter EmpID
		    {
				get
		        {
					if(_EmpID_W == null)
	        	    {
						_EmpID_W = TearOff.EmpID;
					}
					return _EmpID_W;
				}
			}

			public WhereParameter CurrentBank
		    {
				get
		        {
					if(_CurrentBank_W == null)
	        	    {
						_CurrentBank_W = TearOff.CurrentBank;
					}
					return _CurrentBank_W;
				}
			}

			public WhereParameter CreationDate
		    {
				get
		        {
					if(_CreationDate_W == null)
	        	    {
						_CreationDate_W = TearOff.CreationDate;
					}
					return _CreationDate_W;
				}
			}

			public WhereParameter CreatedBy
		    {
				get
		        {
					if(_CreatedBy_W == null)
	        	    {
						_CreatedBy_W = TearOff.CreatedBy;
					}
					return _CreatedBy_W;
				}
			}

			public WhereParameter ModifiedDate
		    {
				get
		        {
					if(_ModifiedDate_W == null)
	        	    {
						_ModifiedDate_W = TearOff.ModifiedDate;
					}
					return _ModifiedDate_W;
				}
			}

			public WhereParameter ModifiedBy
		    {
				get
		        {
					if(_ModifiedBy_W == null)
	        	    {
						_ModifiedBy_W = TearOff.ModifiedBy;
					}
					return _ModifiedBy_W;
				}
			}

			private WhereParameter _ID_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _AccountNo_W = null;
			private WhereParameter _AccountHolder_W = null;
			private WhereParameter _Branch_W = null;
			private WhereParameter _EmpID_W = null;
			private WhereParameter _CurrentBank_W = null;
			private WhereParameter _CreationDate_W = null;
			private WhereParameter _CreatedBy_W = null;
			private WhereParameter _ModifiedDate_W = null;
			private WhereParameter _ModifiedBy_W = null;

			public void WhereClauseReset()
			{
				_ID_W = null;
				_Name_W = null;
				_AccountNo_W = null;
				_AccountHolder_W = null;
				_Branch_W = null;
				_EmpID_W = null;
				_CurrentBank_W = null;
				_CreationDate_W = null;
				_CreatedBy_W = null;
				_ModifiedDate_W = null;
				_ModifiedBy_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ID, Parameters.ID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AccountNo
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AccountNo, Parameters.AccountNo);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AccountHolder
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AccountHolder, Parameters.AccountHolder);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Branch
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Branch, Parameters.Branch);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EmpID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EmpID, Parameters.EmpID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CurrentBank
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CurrentBank, Parameters.CurrentBank);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CreationDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CreationDate, Parameters.CreationDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CreatedBy
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CreatedBy, Parameters.CreatedBy);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ModifiedDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ModifiedDate, Parameters.ModifiedDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ModifiedBy
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ModifiedBy, Parameters.ModifiedBy);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter AccountNo
		    {
				get
		        {
					if(_AccountNo_W == null)
	        	    {
						_AccountNo_W = TearOff.AccountNo;
					}
					return _AccountNo_W;
				}
			}

			public AggregateParameter AccountHolder
		    {
				get
		        {
					if(_AccountHolder_W == null)
	        	    {
						_AccountHolder_W = TearOff.AccountHolder;
					}
					return _AccountHolder_W;
				}
			}

			public AggregateParameter Branch
		    {
				get
		        {
					if(_Branch_W == null)
	        	    {
						_Branch_W = TearOff.Branch;
					}
					return _Branch_W;
				}
			}

			public AggregateParameter EmpID
		    {
				get
		        {
					if(_EmpID_W == null)
	        	    {
						_EmpID_W = TearOff.EmpID;
					}
					return _EmpID_W;
				}
			}

			public AggregateParameter CurrentBank
		    {
				get
		        {
					if(_CurrentBank_W == null)
	        	    {
						_CurrentBank_W = TearOff.CurrentBank;
					}
					return _CurrentBank_W;
				}
			}

			public AggregateParameter CreationDate
		    {
				get
		        {
					if(_CreationDate_W == null)
	        	    {
						_CreationDate_W = TearOff.CreationDate;
					}
					return _CreationDate_W;
				}
			}

			public AggregateParameter CreatedBy
		    {
				get
		        {
					if(_CreatedBy_W == null)
	        	    {
						_CreatedBy_W = TearOff.CreatedBy;
					}
					return _CreatedBy_W;
				}
			}

			public AggregateParameter ModifiedDate
		    {
				get
		        {
					if(_ModifiedDate_W == null)
	        	    {
						_ModifiedDate_W = TearOff.ModifiedDate;
					}
					return _ModifiedDate_W;
				}
			}

			public AggregateParameter ModifiedBy
		    {
				get
		        {
					if(_ModifiedBy_W == null)
	        	    {
						_ModifiedBy_W = TearOff.ModifiedBy;
					}
					return _ModifiedBy_W;
				}
			}

			private AggregateParameter _ID_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _AccountNo_W = null;
			private AggregateParameter _AccountHolder_W = null;
			private AggregateParameter _Branch_W = null;
			private AggregateParameter _EmpID_W = null;
			private AggregateParameter _CurrentBank_W = null;
			private AggregateParameter _CreationDate_W = null;
			private AggregateParameter _CreatedBy_W = null;
			private AggregateParameter _ModifiedDate_W = null;
			private AggregateParameter _ModifiedBy_W = null;

			public void AggregateClauseReset()
			{
				_ID_W = null;
				_Name_W = null;
				_AccountNo_W = null;
				_AccountHolder_W = null;
				_Branch_W = null;
				_EmpID_W = null;
				_CurrentBank_W = null;
				_CreationDate_W = null;
				_CreatedBy_W = null;
				_ModifiedDate_W = null;
				_ModifiedBy_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_BankDetailInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.ID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_BankDetailUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_BankDetailDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.ID);
			p.SourceColumn = ColumnNames.ID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.ID);
			p.SourceColumn = ColumnNames.ID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name);
			p.SourceColumn = ColumnNames.Name;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AccountNo);
			p.SourceColumn = ColumnNames.AccountNo;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AccountHolder);
			p.SourceColumn = ColumnNames.AccountHolder;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Branch);
			p.SourceColumn = ColumnNames.Branch;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EmpID);
			p.SourceColumn = ColumnNames.EmpID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CurrentBank);
			p.SourceColumn = ColumnNames.CurrentBank;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CreationDate);
			p.SourceColumn = ColumnNames.CreationDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CreatedBy);
			p.SourceColumn = ColumnNames.CreatedBy;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ModifiedDate);
			p.SourceColumn = ColumnNames.ModifiedDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ModifiedBy);
			p.SourceColumn = ColumnNames.ModifiedBy;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
