
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.2.0.1)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace HRModuleEntity
{
	public abstract class _ContractDetails : SqlClientEntity
	{
		public _ContractDetails()
		{
			this.QuerySource = "ContractDetails";
			this.MappingName = "ContractDetails";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_ContractDetailsLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(long ID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.ID, ID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_ContractDetailsLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter ID
			{
				get
				{
					return new SqlParameter("@ID", SqlDbType.BigInt, 0);
				}
			}
			
			public static SqlParameter EmpID
			{
				get
				{
					return new SqlParameter("@EmpID", SqlDbType.BigInt, 0);
				}
			}
			
			public static SqlParameter ContractTypeID
			{
				get
				{
					return new SqlParameter("@ContractTypeID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter StartDate
			{
				get
				{
					return new SqlParameter("@StartDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter EndDate
			{
				get
				{
					return new SqlParameter("@EndDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter ProbationPeriod
			{
				get
				{
					return new SqlParameter("@ProbationPeriod", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter NoticeByEmployee
			{
				get
				{
					return new SqlParameter("@NoticeByEmployee", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter NoticeByCompany
			{
				get
				{
					return new SqlParameter("@NoticeByCompany", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter IsCurrent
			{
				get
				{
					return new SqlParameter("@IsCurrent", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter CreationDate
			{
				get
				{
					return new SqlParameter("@CreationDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter CreatedBy
			{
				get
				{
					return new SqlParameter("@CreatedBy", SqlDbType.BigInt, 0);
				}
			}
			
			public static SqlParameter ModifiedDate
			{
				get
				{
					return new SqlParameter("@ModifiedDate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter ModifiedBy
			{
				get
				{
					return new SqlParameter("@ModifiedBy", SqlDbType.BigInt, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string ID = "ID";
            public const string EmpID = "EmpID";
            public const string ContractTypeID = "ContractTypeID";
            public const string StartDate = "StartDate";
            public const string EndDate = "EndDate";
            public const string ProbationPeriod = "ProbationPeriod";
            public const string NoticeByEmployee = "NoticeByEmployee";
            public const string NoticeByCompany = "NoticeByCompany";
            public const string IsCurrent = "IsCurrent";
            public const string CreationDate = "CreationDate";
            public const string CreatedBy = "CreatedBy";
            public const string ModifiedDate = "ModifiedDate";
            public const string ModifiedBy = "ModifiedBy";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ID] = _ContractDetails.PropertyNames.ID;
					ht[EmpID] = _ContractDetails.PropertyNames.EmpID;
					ht[ContractTypeID] = _ContractDetails.PropertyNames.ContractTypeID;
					ht[StartDate] = _ContractDetails.PropertyNames.StartDate;
					ht[EndDate] = _ContractDetails.PropertyNames.EndDate;
					ht[ProbationPeriod] = _ContractDetails.PropertyNames.ProbationPeriod;
					ht[NoticeByEmployee] = _ContractDetails.PropertyNames.NoticeByEmployee;
					ht[NoticeByCompany] = _ContractDetails.PropertyNames.NoticeByCompany;
					ht[IsCurrent] = _ContractDetails.PropertyNames.IsCurrent;
					ht[CreationDate] = _ContractDetails.PropertyNames.CreationDate;
					ht[CreatedBy] = _ContractDetails.PropertyNames.CreatedBy;
					ht[ModifiedDate] = _ContractDetails.PropertyNames.ModifiedDate;
					ht[ModifiedBy] = _ContractDetails.PropertyNames.ModifiedBy;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string ID = "ID";
            public const string EmpID = "EmpID";
            public const string ContractTypeID = "ContractTypeID";
            public const string StartDate = "StartDate";
            public const string EndDate = "EndDate";
            public const string ProbationPeriod = "ProbationPeriod";
            public const string NoticeByEmployee = "NoticeByEmployee";
            public const string NoticeByCompany = "NoticeByCompany";
            public const string IsCurrent = "IsCurrent";
            public const string CreationDate = "CreationDate";
            public const string CreatedBy = "CreatedBy";
            public const string ModifiedDate = "ModifiedDate";
            public const string ModifiedBy = "ModifiedBy";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ID] = _ContractDetails.ColumnNames.ID;
					ht[EmpID] = _ContractDetails.ColumnNames.EmpID;
					ht[ContractTypeID] = _ContractDetails.ColumnNames.ContractTypeID;
					ht[StartDate] = _ContractDetails.ColumnNames.StartDate;
					ht[EndDate] = _ContractDetails.ColumnNames.EndDate;
					ht[ProbationPeriod] = _ContractDetails.ColumnNames.ProbationPeriod;
					ht[NoticeByEmployee] = _ContractDetails.ColumnNames.NoticeByEmployee;
					ht[NoticeByCompany] = _ContractDetails.ColumnNames.NoticeByCompany;
					ht[IsCurrent] = _ContractDetails.ColumnNames.IsCurrent;
					ht[CreationDate] = _ContractDetails.ColumnNames.CreationDate;
					ht[CreatedBy] = _ContractDetails.ColumnNames.CreatedBy;
					ht[ModifiedDate] = _ContractDetails.ColumnNames.ModifiedDate;
					ht[ModifiedBy] = _ContractDetails.ColumnNames.ModifiedBy;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string ID = "s_ID";
            public const string EmpID = "s_EmpID";
            public const string ContractTypeID = "s_ContractTypeID";
            public const string StartDate = "s_StartDate";
            public const string EndDate = "s_EndDate";
            public const string ProbationPeriod = "s_ProbationPeriod";
            public const string NoticeByEmployee = "s_NoticeByEmployee";
            public const string NoticeByCompany = "s_NoticeByCompany";
            public const string IsCurrent = "s_IsCurrent";
            public const string CreationDate = "s_CreationDate";
            public const string CreatedBy = "s_CreatedBy";
            public const string ModifiedDate = "s_ModifiedDate";
            public const string ModifiedBy = "s_ModifiedBy";

		}
		#endregion		
		
		#region Properties
	
		public virtual long ID
	    {
			get
	        {
				return base.Getlong(ColumnNames.ID);
			}
			set
	        {
				base.Setlong(ColumnNames.ID, value);
			}
		}

		public virtual long EmpID
	    {
			get
	        {
				return base.Getlong(ColumnNames.EmpID);
			}
			set
	        {
				base.Setlong(ColumnNames.EmpID, value);
			}
		}

		public virtual int ContractTypeID
	    {
			get
	        {
				return base.Getint(ColumnNames.ContractTypeID);
			}
			set
	        {
				base.Setint(ColumnNames.ContractTypeID, value);
			}
		}

		public virtual DateTime StartDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.StartDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.StartDate, value);
			}
		}

		public virtual DateTime EndDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.EndDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.EndDate, value);
			}
		}

		public virtual int ProbationPeriod
	    {
			get
	        {
				return base.Getint(ColumnNames.ProbationPeriod);
			}
			set
	        {
				base.Setint(ColumnNames.ProbationPeriod, value);
			}
		}

		public virtual int NoticeByEmployee
	    {
			get
	        {
				return base.Getint(ColumnNames.NoticeByEmployee);
			}
			set
	        {
				base.Setint(ColumnNames.NoticeByEmployee, value);
			}
		}

		public virtual int NoticeByCompany
	    {
			get
	        {
				return base.Getint(ColumnNames.NoticeByCompany);
			}
			set
	        {
				base.Setint(ColumnNames.NoticeByCompany, value);
			}
		}

		public virtual bool IsCurrent
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsCurrent);
			}
			set
	        {
				base.Setbool(ColumnNames.IsCurrent, value);
			}
		}

		public virtual DateTime CreationDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.CreationDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.CreationDate, value);
			}
		}

		public virtual long CreatedBy
	    {
			get
	        {
				return base.Getlong(ColumnNames.CreatedBy);
			}
			set
	        {
				base.Setlong(ColumnNames.CreatedBy, value);
			}
		}

		public virtual DateTime ModifiedDate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.ModifiedDate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.ModifiedDate, value);
			}
		}

		public virtual long ModifiedBy
	    {
			get
	        {
				return base.Getlong(ColumnNames.ModifiedBy);
			}
			set
	        {
				base.Setlong(ColumnNames.ModifiedBy, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_ID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ID) ? string.Empty : base.GetlongAsString(ColumnNames.ID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ID);
				else
					this.ID = base.SetlongAsString(ColumnNames.ID, value);
			}
		}

		public virtual string s_EmpID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EmpID) ? string.Empty : base.GetlongAsString(ColumnNames.EmpID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EmpID);
				else
					this.EmpID = base.SetlongAsString(ColumnNames.EmpID, value);
			}
		}

		public virtual string s_ContractTypeID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ContractTypeID) ? string.Empty : base.GetintAsString(ColumnNames.ContractTypeID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ContractTypeID);
				else
					this.ContractTypeID = base.SetintAsString(ColumnNames.ContractTypeID, value);
			}
		}

		public virtual string s_StartDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.StartDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.StartDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.StartDate);
				else
					this.StartDate = base.SetDateTimeAsString(ColumnNames.StartDate, value);
			}
		}

		public virtual string s_EndDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EndDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.EndDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EndDate);
				else
					this.EndDate = base.SetDateTimeAsString(ColumnNames.EndDate, value);
			}
		}

		public virtual string s_ProbationPeriod
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ProbationPeriod) ? string.Empty : base.GetintAsString(ColumnNames.ProbationPeriod);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ProbationPeriod);
				else
					this.ProbationPeriod = base.SetintAsString(ColumnNames.ProbationPeriod, value);
			}
		}

		public virtual string s_NoticeByEmployee
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NoticeByEmployee) ? string.Empty : base.GetintAsString(ColumnNames.NoticeByEmployee);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NoticeByEmployee);
				else
					this.NoticeByEmployee = base.SetintAsString(ColumnNames.NoticeByEmployee, value);
			}
		}

		public virtual string s_NoticeByCompany
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NoticeByCompany) ? string.Empty : base.GetintAsString(ColumnNames.NoticeByCompany);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NoticeByCompany);
				else
					this.NoticeByCompany = base.SetintAsString(ColumnNames.NoticeByCompany, value);
			}
		}

		public virtual string s_IsCurrent
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsCurrent) ? string.Empty : base.GetboolAsString(ColumnNames.IsCurrent);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsCurrent);
				else
					this.IsCurrent = base.SetboolAsString(ColumnNames.IsCurrent, value);
			}
		}

		public virtual string s_CreationDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CreationDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.CreationDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CreationDate);
				else
					this.CreationDate = base.SetDateTimeAsString(ColumnNames.CreationDate, value);
			}
		}

		public virtual string s_CreatedBy
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CreatedBy) ? string.Empty : base.GetlongAsString(ColumnNames.CreatedBy);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CreatedBy);
				else
					this.CreatedBy = base.SetlongAsString(ColumnNames.CreatedBy, value);
			}
		}

		public virtual string s_ModifiedDate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ModifiedDate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.ModifiedDate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ModifiedDate);
				else
					this.ModifiedDate = base.SetDateTimeAsString(ColumnNames.ModifiedDate, value);
			}
		}

		public virtual string s_ModifiedBy
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ModifiedBy) ? string.Empty : base.GetlongAsString(ColumnNames.ModifiedBy);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ModifiedBy);
				else
					this.ModifiedBy = base.SetlongAsString(ColumnNames.ModifiedBy, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ID, Parameters.ID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EmpID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EmpID, Parameters.EmpID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ContractTypeID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ContractTypeID, Parameters.ContractTypeID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter StartDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.StartDate, Parameters.StartDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EndDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EndDate, Parameters.EndDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ProbationPeriod
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ProbationPeriod, Parameters.ProbationPeriod);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NoticeByEmployee
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NoticeByEmployee, Parameters.NoticeByEmployee);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NoticeByCompany
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NoticeByCompany, Parameters.NoticeByCompany);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsCurrent
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsCurrent, Parameters.IsCurrent);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CreationDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CreationDate, Parameters.CreationDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CreatedBy
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CreatedBy, Parameters.CreatedBy);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ModifiedDate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ModifiedDate, Parameters.ModifiedDate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ModifiedBy
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ModifiedBy, Parameters.ModifiedBy);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public WhereParameter EmpID
		    {
				get
		        {
					if(_EmpID_W == null)
	        	    {
						_EmpID_W = TearOff.EmpID;
					}
					return _EmpID_W;
				}
			}

			public WhereParameter ContractTypeID
		    {
				get
		        {
					if(_ContractTypeID_W == null)
	        	    {
						_ContractTypeID_W = TearOff.ContractTypeID;
					}
					return _ContractTypeID_W;
				}
			}

			public WhereParameter StartDate
		    {
				get
		        {
					if(_StartDate_W == null)
	        	    {
						_StartDate_W = TearOff.StartDate;
					}
					return _StartDate_W;
				}
			}

			public WhereParameter EndDate
		    {
				get
		        {
					if(_EndDate_W == null)
	        	    {
						_EndDate_W = TearOff.EndDate;
					}
					return _EndDate_W;
				}
			}

			public WhereParameter ProbationPeriod
		    {
				get
		        {
					if(_ProbationPeriod_W == null)
	        	    {
						_ProbationPeriod_W = TearOff.ProbationPeriod;
					}
					return _ProbationPeriod_W;
				}
			}

			public WhereParameter NoticeByEmployee
		    {
				get
		        {
					if(_NoticeByEmployee_W == null)
	        	    {
						_NoticeByEmployee_W = TearOff.NoticeByEmployee;
					}
					return _NoticeByEmployee_W;
				}
			}

			public WhereParameter NoticeByCompany
		    {
				get
		        {
					if(_NoticeByCompany_W == null)
	        	    {
						_NoticeByCompany_W = TearOff.NoticeByCompany;
					}
					return _NoticeByCompany_W;
				}
			}

			public WhereParameter IsCurrent
		    {
				get
		        {
					if(_IsCurrent_W == null)
	        	    {
						_IsCurrent_W = TearOff.IsCurrent;
					}
					return _IsCurrent_W;
				}
			}

			public WhereParameter CreationDate
		    {
				get
		        {
					if(_CreationDate_W == null)
	        	    {
						_CreationDate_W = TearOff.CreationDate;
					}
					return _CreationDate_W;
				}
			}

			public WhereParameter CreatedBy
		    {
				get
		        {
					if(_CreatedBy_W == null)
	        	    {
						_CreatedBy_W = TearOff.CreatedBy;
					}
					return _CreatedBy_W;
				}
			}

			public WhereParameter ModifiedDate
		    {
				get
		        {
					if(_ModifiedDate_W == null)
	        	    {
						_ModifiedDate_W = TearOff.ModifiedDate;
					}
					return _ModifiedDate_W;
				}
			}

			public WhereParameter ModifiedBy
		    {
				get
		        {
					if(_ModifiedBy_W == null)
	        	    {
						_ModifiedBy_W = TearOff.ModifiedBy;
					}
					return _ModifiedBy_W;
				}
			}

			private WhereParameter _ID_W = null;
			private WhereParameter _EmpID_W = null;
			private WhereParameter _ContractTypeID_W = null;
			private WhereParameter _StartDate_W = null;
			private WhereParameter _EndDate_W = null;
			private WhereParameter _ProbationPeriod_W = null;
			private WhereParameter _NoticeByEmployee_W = null;
			private WhereParameter _NoticeByCompany_W = null;
			private WhereParameter _IsCurrent_W = null;
			private WhereParameter _CreationDate_W = null;
			private WhereParameter _CreatedBy_W = null;
			private WhereParameter _ModifiedDate_W = null;
			private WhereParameter _ModifiedBy_W = null;

			public void WhereClauseReset()
			{
				_ID_W = null;
				_EmpID_W = null;
				_ContractTypeID_W = null;
				_StartDate_W = null;
				_EndDate_W = null;
				_ProbationPeriod_W = null;
				_NoticeByEmployee_W = null;
				_NoticeByCompany_W = null;
				_IsCurrent_W = null;
				_CreationDate_W = null;
				_CreatedBy_W = null;
				_ModifiedDate_W = null;
				_ModifiedBy_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ID, Parameters.ID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EmpID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EmpID, Parameters.EmpID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ContractTypeID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ContractTypeID, Parameters.ContractTypeID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter StartDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.StartDate, Parameters.StartDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EndDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EndDate, Parameters.EndDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ProbationPeriod
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ProbationPeriod, Parameters.ProbationPeriod);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NoticeByEmployee
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NoticeByEmployee, Parameters.NoticeByEmployee);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NoticeByCompany
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NoticeByCompany, Parameters.NoticeByCompany);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsCurrent
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsCurrent, Parameters.IsCurrent);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CreationDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CreationDate, Parameters.CreationDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CreatedBy
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CreatedBy, Parameters.CreatedBy);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ModifiedDate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ModifiedDate, Parameters.ModifiedDate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ModifiedBy
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ModifiedBy, Parameters.ModifiedBy);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public AggregateParameter EmpID
		    {
				get
		        {
					if(_EmpID_W == null)
	        	    {
						_EmpID_W = TearOff.EmpID;
					}
					return _EmpID_W;
				}
			}

			public AggregateParameter ContractTypeID
		    {
				get
		        {
					if(_ContractTypeID_W == null)
	        	    {
						_ContractTypeID_W = TearOff.ContractTypeID;
					}
					return _ContractTypeID_W;
				}
			}

			public AggregateParameter StartDate
		    {
				get
		        {
					if(_StartDate_W == null)
	        	    {
						_StartDate_W = TearOff.StartDate;
					}
					return _StartDate_W;
				}
			}

			public AggregateParameter EndDate
		    {
				get
		        {
					if(_EndDate_W == null)
	        	    {
						_EndDate_W = TearOff.EndDate;
					}
					return _EndDate_W;
				}
			}

			public AggregateParameter ProbationPeriod
		    {
				get
		        {
					if(_ProbationPeriod_W == null)
	        	    {
						_ProbationPeriod_W = TearOff.ProbationPeriod;
					}
					return _ProbationPeriod_W;
				}
			}

			public AggregateParameter NoticeByEmployee
		    {
				get
		        {
					if(_NoticeByEmployee_W == null)
	        	    {
						_NoticeByEmployee_W = TearOff.NoticeByEmployee;
					}
					return _NoticeByEmployee_W;
				}
			}

			public AggregateParameter NoticeByCompany
		    {
				get
		        {
					if(_NoticeByCompany_W == null)
	        	    {
						_NoticeByCompany_W = TearOff.NoticeByCompany;
					}
					return _NoticeByCompany_W;
				}
			}

			public AggregateParameter IsCurrent
		    {
				get
		        {
					if(_IsCurrent_W == null)
	        	    {
						_IsCurrent_W = TearOff.IsCurrent;
					}
					return _IsCurrent_W;
				}
			}

			public AggregateParameter CreationDate
		    {
				get
		        {
					if(_CreationDate_W == null)
	        	    {
						_CreationDate_W = TearOff.CreationDate;
					}
					return _CreationDate_W;
				}
			}

			public AggregateParameter CreatedBy
		    {
				get
		        {
					if(_CreatedBy_W == null)
	        	    {
						_CreatedBy_W = TearOff.CreatedBy;
					}
					return _CreatedBy_W;
				}
			}

			public AggregateParameter ModifiedDate
		    {
				get
		        {
					if(_ModifiedDate_W == null)
	        	    {
						_ModifiedDate_W = TearOff.ModifiedDate;
					}
					return _ModifiedDate_W;
				}
			}

			public AggregateParameter ModifiedBy
		    {
				get
		        {
					if(_ModifiedBy_W == null)
	        	    {
						_ModifiedBy_W = TearOff.ModifiedBy;
					}
					return _ModifiedBy_W;
				}
			}

			private AggregateParameter _ID_W = null;
			private AggregateParameter _EmpID_W = null;
			private AggregateParameter _ContractTypeID_W = null;
			private AggregateParameter _StartDate_W = null;
			private AggregateParameter _EndDate_W = null;
			private AggregateParameter _ProbationPeriod_W = null;
			private AggregateParameter _NoticeByEmployee_W = null;
			private AggregateParameter _NoticeByCompany_W = null;
			private AggregateParameter _IsCurrent_W = null;
			private AggregateParameter _CreationDate_W = null;
			private AggregateParameter _CreatedBy_W = null;
			private AggregateParameter _ModifiedDate_W = null;
			private AggregateParameter _ModifiedBy_W = null;

			public void AggregateClauseReset()
			{
				_ID_W = null;
				_EmpID_W = null;
				_ContractTypeID_W = null;
				_StartDate_W = null;
				_EndDate_W = null;
				_ProbationPeriod_W = null;
				_NoticeByEmployee_W = null;
				_NoticeByCompany_W = null;
				_IsCurrent_W = null;
				_CreationDate_W = null;
				_CreatedBy_W = null;
				_ModifiedDate_W = null;
				_ModifiedBy_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_ContractDetailsInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.ID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_ContractDetailsUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_ContractDetailsDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.ID);
			p.SourceColumn = ColumnNames.ID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.ID);
			p.SourceColumn = ColumnNames.ID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EmpID);
			p.SourceColumn = ColumnNames.EmpID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ContractTypeID);
			p.SourceColumn = ColumnNames.ContractTypeID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.StartDate);
			p.SourceColumn = ColumnNames.StartDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EndDate);
			p.SourceColumn = ColumnNames.EndDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ProbationPeriod);
			p.SourceColumn = ColumnNames.ProbationPeriod;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NoticeByEmployee);
			p.SourceColumn = ColumnNames.NoticeByEmployee;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NoticeByCompany);
			p.SourceColumn = ColumnNames.NoticeByCompany;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsCurrent);
			p.SourceColumn = ColumnNames.IsCurrent;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CreationDate);
			p.SourceColumn = ColumnNames.CreationDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CreatedBy);
			p.SourceColumn = ColumnNames.CreatedBy;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ModifiedDate);
			p.SourceColumn = ColumnNames.ModifiedDate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ModifiedBy);
			p.SourceColumn = ColumnNames.ModifiedBy;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
