
// Generated by MyGeneration Version # (1.2.0.1)

using System;
using HRModuleEntity;

namespace HRModuleBL
{
	public class ExtraFinancial : _ExtraFinancial
	{
		public ExtraFinancial()
		{
		
		}
	}
}
