
// Generated by MyGeneration Version # (1.2.0.1)

using System;
using HRModuleEntity;

namespace HRModuleBL
{
	public class PaymentStrategy : _PaymentStrategy
	{
		public PaymentStrategy()
		{
		
		}
	}
}
